---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild
# description will be included in the image's metadata
description: A bluebuild image focused on Niri

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - che/nerd-fonts
        - errornointernet/packages
        - solopasha/hyprland
        - yalter/niri
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      nonfree: negativo17
    install:
      packages:
        - install-weak-deps: false
          packages:
            - qalculate-gtk
            - kitty
            - fira-code-fonts
            - fontawesome-fonts
            - fuzzel
            - gnome-keyring
            - nautilus
            - mako
            - mupdf
            - mpv
            - nerd-fonts
            - pipewire-plugin-libcamera
            - powerline-fonts
            - solaar
            - swappy
            - wlsunset
            - wl-clipboard
            - wl-mirror
            - wev
            # (mine) utils:
            - bat
            - ddcutil
            - difftastic
            - dutree
            - erofs-utils
            - eza
            - fd-find
            - fish
            - fzf
            - gdb
            - git-delta
            - gparted
            - guestfs-tools
            - perl
            - playerctl
            - policycoreutils
            - ripgrep
            - qemu-kvm
            - syncthing
            - udiskie
            - valgrind
            - zenity
            # (mine) external repos:
            - tailscale
            - starship
            - nwg-clipman
            - waybar-git
            - niri
            - xwayland-satellite
            - cliphist
            - ripdrag
            - satty
            - scrcpy
            - swww
            - try
            - walker
            - quickshell
          remove:
            - firefox # default firefox removed in favor of flatpak
            - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
            - waybar
  
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

