---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild
# description will be included in the image's metadata
description: A bluebuild image focused on Niri

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - che/nerd-fonts
        - errornointernet/packages
        - errornointernet/quickshell
        - solopasha/hyprland
        - yalter/niri
        - avengemedia/dms
        - scottames/vicinae
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      nonfree: negativo17
    install:
      install-weak-deps: true
      packages:
        - qalculate-gtk
        - kitty
        - fcitx5-chinese-addons
        - fcitx5-configtool
        - fira-code-fonts
        - fontawesome-fonts
        - fuzzel
        - gnome-keyring
        - nautilus
        - mako
        - mupdf
        - mpv
        - nerd-fonts
        - pipewire-plugin-libcamera
        - powerline-fonts
        - solaar
        - swappy
        - wlsunset
        - wl-clipboard
        - wl-mirror
        - wev
        # (mine) utils:
        - bat
        - ddcutil
        - difftastic
        - dutree
        - erofs-utils
        - eza
        - fd-find
        - fish
        - fzf
        - gdb
        - git-delta
        - gparted
        - guestfs-tools
        - perl
        - playerctl
        - policycoreutils
        - ripgrep
        - qemu-kvm
        - seahorse
        - swayidle
        - syncthing
        - udiskie
        - valgrind
        - zenity
        # (mine) external repos:
        - tailscale
        - starship
        - nwg-clipman
        - waybar-git
        - niri
        - xwayland-satellite
        - cliphist
        - ripdrag
        - satty
        - scrcpy
        - swww
        - try
        - walker
        - elephant
        - quickshell
        - dms
        - dms-greeter
        - vicinae
        # to review (copied from ublue-niri)
        - dbus-daemon
        - wireplumber
        - pipewire
        - heif-pixbuf-loader
        - libfdk-aac
        - gstreamer1-plugins-bad
        - gstreamer1-plugins-ugly
        - greetd
        - greetd-selinux
        - adw-gtk3-theme
        - android-tools

    remove:
      packages:
        - firefox # default firefox removed in favor of flatpak
        - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
        - waybar

  # - type: default-flatpaks
  #   source: ghcr.io/blue-build/modules:pr-514
  #   configurations:
  #     - notify: false
  #       scope: system
  #       install:
  #         - org.mozilla.firefox
  #         - org.gnome.Loupe
  #         - xyz.armcord.ArmCord
  #         - io.github.celluloid_player.Celluloid
  #         - com.bitwarden.desktop
  #         - com.slack.Slack
  #         - com.sublimemerge.App
  #         - com.visualstudio.code-oss
  #         - fr.handbrake.ghb
  #         - md.obsidian.Obsidian
  #         - com.microsoft.Edge
  #         - org.telegram.desktop
  #         - org.videolan.VLC
  #         - app.drey.Warp
  #         - app.getclipboard.Clipboard
  #         - org.pipewire.Helvum
  #         - com.github.wwmm.easyeffects
  #         - io.github.nokse22.minitext
  #         - dev.serebit.Waycheck
  #         - org.mozilla.Thunderbird
  #         - org.gnome.Fractal
  #         - net.sapples.LiveCaptions
  #         - com.github.tenderowl.frog
  #         - com.github.jeromerobert.pdfarranger
  #         - org.gnome.Weather
  #         - com.github.qarmin.czkawka
  #         - org.gnome.SimpleScan
  #         - com.github.tchx84.Flatseal
  #         - dev.zed.Zed
  #         - org.signal.Signal
  #         - io.github.flattool.Warehouse
  #         - com.github.rafostar.Clapper
  #         # to review
  #         - com.belmoussaoui.Decoder
  #         - com.github.ahrm.sioyek
  #         - com.github.finefindus.eyedropper
  #         - com.github.k4zmu2a.spacecadetpinball
  #         - com.quexten.Goldwarden
  #         - com.rtosta.zapzap
  #         - com.transmissionbt.Transmission
  #         - dev.alextren.Spot
  #         - dev.lapce.lapce
  #         - io.github.alainm23.planify
  #         - io.github.amit9838.mousam
  #         - io.github.hrkfdn.ncspot
  #         - io.github.seadve.Kooha
  #         - io.missioncenter.MissionCenter
  #         - io.qt.qdbusviewer
  #         - net.ankiweb.Anki
  #         - net.mkiol.SpeechNote
  #         - org.cubocore.CorePDF
  #         - org.fedoraproject.MediaWriter
  #         - org.gnome.Calendar
  #         - org.gnome.Evolution
  #         - org.gnome.Maps
  #         - org.gnome.Snapshot
  #         - org.gnome.clocks
  #         - org.gnome.gitlab.dqpb.GMetronome
  #         - org.gnome.meld
  #         - org.kde.digikam
  #         - org.kde.skanpage
  #         - org.libvips.vipsdisp
  #         - org.tenacityaudio.Tenacity
  #         - us.zoom.Zoom
  #         - xyz.tytanium.DoorKnocker

  - type: systemd
    user:
      enabled:
        - greetd
      disabled:
        - gdm sddm lightdm

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

