---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild
# description will be included in the image's metadata
description: A bluebuild image focused on Niri

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-%OS_VERSION%/che-nerd-fonts-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/errornointernet/packages/repo/fedora-%OS_VERSION%/errornointernet-packages-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/errornointernet/walker/repo/fedora-%OS_VERSION%/errornointernet-walker-fedora-%OS_VERSION%.repo
    install:
      packages:
        - install-weak-deps: false
          packages:
            - qalculate-gtk
            - kitty
            - fira-code-fonts
            - fontawesome-fonts
            - fuzzel
            - grim
            - gnome-keyring
            - nautilus
            - mako
            - mupdf
            - mpv
            - nerd-fonts
            - pipewire-plugin-libcamera
            - powerline-fonts
            - slurp
            - solaar
            - swappy
            - squeekboard
            - wlsunset
            - wl-clipboard
            - wl-mirror
            - wev
            - wtype
            # (mine) utils:
            - bat
            - ddcutil
            - difftastic
            - dutree
            - erofs-utils
            - eza
            - fd-find
            - fish
            - fzf
            - gdb
            - git-delta
            - gparted
            - guestfs-tools
            - ncdu
            - perl
            - playerctl
            - policycoreutils
            - ranger
            - ripgrep
            - qemu-kvm
            - syncthing
            - udiskie
            - valgrind
            - zenity
            # (mine) external repos:
            - eww-wayland-git
            - aylurs-gtk-shell
            - tailscale
            - hypridle
            - hyprland
            - hyprland-contrib
            # - hyprland-plugins
            - hyprlock
            - hyprpicker
            - hyprshot
            - hyprpaper
            - starship
            - nwg-clipman
            - xdg-desktop-portal-hyprland
            - waybar-git
            # niri
            - niri
            # cosmic
            - cosmic-desktop
            - xwayland-satellite
            - cliphist
            - ripdrag
            - satty
            - scrcpy
            - try
            - walker
            - quickshell
          remove:
            - firefox # default firefox removed in favor of flatpak
            - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
            - waybar
  
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

